import = [ "~/.config/alacritty/everforest_dark.toml" ]

[font]
size = 14
offset.y = 1
offset.x = 0

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[window]
padding = { x = 12, y = 12 }
opacity = 0.93
